services:
  - type: web
    name: cafeteria-backend
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    rootDir: ./backend_Cafeteria
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_PATH
        value: ./data/cafeteria.db